/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ie.interfazgrafica;

/**
 *
 * @author Valentina
 */
public class VentanaBatalla extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBatalla
     */
    public VentanaBatalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DatosBatalla = new javax.swing.JPanel();
        lblBatallaActual = new javax.swing.JLabel();
        lblTurnoActual = new javax.swing.JLabel();
        PanelJugador1 = new javax.swing.JPanel();
        lblJugador1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblVida1 = new javax.swing.JLabel();
        lblBendicion1 = new javax.swing.JLabel();
        lblArma1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        pbVida1 = new javax.swing.JProgressBar();
        pbBendicion1 = new javax.swing.JProgressBar();
        PanelJugador2 = new javax.swing.JPanel();
        lblJugador2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblVida2 = new javax.swing.JLabel();
        lblBendicion2 = new javax.swing.JLabel();
        lblArma2 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        pbVida2 = new javax.swing.JProgressBar();
        pbBendicion2 = new javax.swing.JProgressBar();
        panelEventos = new javax.swing.JPanel();
        lblLog = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Pausar = new javax.swing.JMenuItem();
        GuardarPartida = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        HistorialPartidas = new javax.swing.JMenuItem();
        Estadisticas = new javax.swing.JMenuItem();
        Ranking = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DatosBatalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));

        lblBatallaActual.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lblBatallaActual.setText("Batalla actual:");

        lblTurnoActual.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lblTurnoActual.setText("Turno actual:");

        javax.swing.GroupLayout DatosBatallaLayout = new javax.swing.GroupLayout(DatosBatalla);
        DatosBatalla.setLayout(DatosBatallaLayout);
        DatosBatallaLayout.setHorizontalGroup(
            DatosBatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosBatallaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBatallaActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTurnoActual)
                .addGap(141, 141, 141))
        );
        DatosBatallaLayout.setVerticalGroup(
            DatosBatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosBatallaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosBatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBatallaActual)
                    .addComponent(lblTurnoActual))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));

        lblJugador1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lblJugador1.setForeground(new java.awt.Color(0, 102, 0));
        lblJugador1.setText("JUGADOR 1");

        lblNombre1.setText("Nombre:");

        lblVida1.setText("Vida:");

        lblBendicion1.setText("Bendicion:");

        lblArma1.setText("Arma:");

        lblEstado1.setText("Estado:");

        javax.swing.GroupLayout PanelJugador1Layout = new javax.swing.GroupLayout(PanelJugador1);
        PanelJugador1.setLayout(PanelJugador1Layout);
        PanelJugador1Layout.setHorizontalGroup(
            PanelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugador1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre1)
                    .addGroup(PanelJugador1Layout.createSequentialGroup()
                        .addComponent(lblBendicion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbBendicion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblArma1)
                    .addComponent(lblEstado1)
                    .addGroup(PanelJugador1Layout.createSequentialGroup()
                        .addComponent(lblVida1)
                        .addGap(18, 18, 18)
                        .addComponent(pbVida1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJugador1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJugador1)
                .addGap(101, 101, 101))
        );
        PanelJugador1Layout.setVerticalGroup(
            PanelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugador1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblJugador1)
                .addGap(18, 18, 18)
                .addComponent(lblNombre1)
                .addGap(18, 18, 18)
                .addGroup(PanelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVida1)
                    .addComponent(pbVida1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBendicion1)
                    .addComponent(pbBendicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblArma1)
                .addGap(18, 18, 18)
                .addComponent(lblEstado1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        PanelJugador2.setPreferredSize(new java.awt.Dimension(282, 318));

        lblJugador2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lblJugador2.setForeground(new java.awt.Color(0, 102, 0));
        lblJugador2.setText("JUGADOR 2");

        lblNombre2.setText("Nombre:");

        lblVida2.setText("Vida:");

        lblBendicion2.setText("Bendicion:");

        lblArma2.setText("Arma:");

        lblEstado2.setText("Estado:");

        javax.swing.GroupLayout PanelJugador2Layout = new javax.swing.GroupLayout(PanelJugador2);
        PanelJugador2.setLayout(PanelJugador2Layout);
        PanelJugador2Layout.setHorizontalGroup(
            PanelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugador2Layout.createSequentialGroup()
                .addGroup(PanelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJugador2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PanelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelJugador2Layout.createSequentialGroup()
                                .addComponent(lblVida2)
                                .addGap(18, 18, 18)
                                .addComponent(pbVida2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombre2)
                            .addGroup(PanelJugador2Layout.createSequentialGroup()
                                .addComponent(lblBendicion2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pbBendicion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblArma2)
                            .addComponent(lblEstado2)))
                    .addGroup(PanelJugador2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblJugador2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelJugador2Layout.setVerticalGroup(
            PanelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugador2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblJugador2)
                .addGap(18, 18, 18)
                .addComponent(lblNombre2)
                .addGap(18, 18, 18)
                .addGroup(PanelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVida2)
                    .addComponent(pbVida2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBendicion2)
                    .addComponent(pbBendicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblArma2)
                .addGap(18, 18, 18)
                .addComponent(lblEstado2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelEventos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));

        lblLog.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lblLog.setForeground(new java.awt.Color(0, 102, 0));
        lblLog.setText("Log de eventos:");

        javax.swing.GroupLayout panelEventosLayout = new javax.swing.GroupLayout(panelEventos);
        panelEventos.setLayout(panelEventosLayout);
        panelEventosLayout.setHorizontalGroup(
            panelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEventosLayout.setVerticalGroup(
            panelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLog)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DatosBatalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(PanelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(PanelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatosBatalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenu1.setText("Partida");
        jMenu1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        Pausar.setText("Pausar");
        jMenu1.add(Pausar);

        GuardarPartida.setText("Guardar partida");
        jMenu1.add(GuardarPartida);

        Salir.setText("Salir");
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");
        jMenu2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        HistorialPartidas.setText("Historial de partidas");
        HistorialPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialPartidasActionPerformed(evt);
            }
        });
        jMenu2.add(HistorialPartidas);

        Estadisticas.setText("Estadisticas generales");
        Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasActionPerformed(evt);
            }
        });
        jMenu2.add(Estadisticas);

        Ranking.setText("Ranking de personajes");
        Ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingActionPerformed(evt);
            }
        });
        jMenu2.add(Ranking);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistorialPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialPartidasActionPerformed
        VentanaReportes ventana = new VentanaReportes();
        ventana.setVisible(true);
    }//GEN-LAST:event_HistorialPartidasActionPerformed

    private void EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasActionPerformed
        VentanaReportes ventana = new VentanaReportes();
        ventana.setVisible(true);
    }//GEN-LAST:event_EstadisticasActionPerformed

    private void RankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingActionPerformed
        VentanaReportes ventana = new VentanaReportes();
        ventana.setVisible(true);
    }//GEN-LAST:event_RankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBatalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosBatalla;
    private javax.swing.JMenuItem Estadisticas;
    private javax.swing.JMenuItem GuardarPartida;
    private javax.swing.JMenuItem HistorialPartidas;
    private javax.swing.JPanel PanelJugador1;
    private javax.swing.JPanel PanelJugador2;
    private javax.swing.JMenuItem Pausar;
    private javax.swing.JMenuItem Ranking;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArma1;
    private javax.swing.JLabel lblArma2;
    private javax.swing.JLabel lblBatallaActual;
    private javax.swing.JLabel lblBendicion1;
    private javax.swing.JLabel lblBendicion2;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblTurnoActual;
    private javax.swing.JLabel lblVida1;
    private javax.swing.JLabel lblVida2;
    private javax.swing.JPanel panelEventos;
    private javax.swing.JProgressBar pbBendicion1;
    private javax.swing.JProgressBar pbBendicion2;
    private javax.swing.JProgressBar pbVida1;
    private javax.swing.JProgressBar pbVida2;
    // End of variables declaration//GEN-END:variables
}
