/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ie.interfazgrafica.vistas;
import javax.swing.JTable;
import javax.swing.JLabel;
/**
 *
 * @author Valentina
 */
public class VentanaReportes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
    }
    // === GETTERS PARA CONTROLADOR ===
    public JTable getTablaRanking() { return jTable1; }

    public JLabel getLblMayorDaño() { return lblMayorDaño; }
    public JLabel getLblBatallaLarga() { return lblBatallaLarga; }
    public JLabel getLblArmasInvocadas1() { return lblArmasInvocadas1; }
    public JLabel getLblAtaquesEjecutados() { return lblAtaquesEjecutados; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRanking = new javax.swing.JPanel();
        lblHistorial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelEstadistica = new javax.swing.JPanel();
        lblHistorial1 = new javax.swing.JLabel();
        lblBatallaLarga = new javax.swing.JLabel();
        lblMayorDaño = new javax.swing.JLabel();
        lblAtaquesEjecutados = new javax.swing.JLabel();
        lblArmasInvocadas1 = new javax.swing.JLabel();
        PanelHistorial = new javax.swing.JPanel();
        lblHistorial2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRanking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        lblHistorial.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblHistorial.setForeground(new java.awt.Color(0, 102, 0));
        lblHistorial.setText("RANKING DE PERSONAJES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apodo", "Tipo", "Vida Final", "Victorias", "Ataques Usados"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout PanelRankingLayout = new javax.swing.GroupLayout(PanelRanking);
        PanelRanking.setLayout(PanelRankingLayout);
        PanelRankingLayout.setHorizontalGroup(
            PanelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelRankingLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lblHistorial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRankingLayout.setVerticalGroup(
            PanelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRankingLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        PanelEstadistica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        lblHistorial1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblHistorial1.setForeground(new java.awt.Color(0, 102, 0));
        lblHistorial1.setText("ESTADISTICAS GENERALES");

        lblBatallaLarga.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblBatallaLarga.setText("Batalla mas larga:");

        lblMayorDaño.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblMayorDaño.setText("Mayor daño en un solo ataque:");

        lblAtaquesEjecutados.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblAtaquesEjecutados.setText("Ataques supremos ejecutados:");

        lblArmasInvocadas1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblArmasInvocadas1.setText("Total de armas invocadas:");

        javax.swing.GroupLayout PanelEstadisticaLayout = new javax.swing.GroupLayout(PanelEstadistica);
        PanelEstadistica.setLayout(PanelEstadisticaLayout);
        PanelEstadisticaLayout.setHorizontalGroup(
            PanelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadisticaLayout.createSequentialGroup()
                .addGroup(PanelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstadisticaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAtaquesEjecutados)
                            .addComponent(lblBatallaLarga)
                            .addComponent(lblArmasInvocadas1)
                            .addComponent(lblMayorDaño)))
                    .addGroup(PanelEstadisticaLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(lblHistorial1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEstadisticaLayout.setVerticalGroup(
            PanelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadisticaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblHistorial1)
                .addGap(18, 18, 18)
                .addComponent(lblMayorDaño)
                .addGap(18, 18, 18)
                .addComponent(lblBatallaLarga)
                .addGap(18, 18, 18)
                .addComponent(lblArmasInvocadas1)
                .addGap(18, 18, 18)
                .addComponent(lblAtaquesEjecutados)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        PanelHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        lblHistorial2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblHistorial2.setForeground(new java.awt.Color(0, 102, 0));
        lblHistorial2.setText("HISTORIAL DE BATALLAS");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout PanelHistorialLayout = new javax.swing.GroupLayout(PanelHistorial);
        PanelHistorial.setLayout(PanelHistorialLayout);
        PanelHistorialLayout.setHorizontalGroup(
            PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(lblHistorial2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        PanelHistorialLayout.setVerticalGroup(
            PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblHistorial2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReportes().setVisible(true);
            }
        });
    }
    public javax.swing.JTextArea getTxtHistorial() {
    return jTextArea2;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEstadistica;
    private javax.swing.JPanel PanelHistorial;
    private javax.swing.JPanel PanelRanking;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblArmasInvocadas1;
    private javax.swing.JLabel lblAtaquesEjecutados;
    private javax.swing.JLabel lblBatallaLarga;
    private javax.swing.JLabel lblHistorial;
    private javax.swing.JLabel lblHistorial1;
    private javax.swing.JLabel lblHistorial2;
    private javax.swing.JLabel lblMayorDaño;
    // End of variables declaration//GEN-END:variables
}
